project:
  type: website
  output-dir: site

website:
  title: "Proteomics blog"
  image: "https://lkittinun.github.io/Proteomics/thumbnail_1.png"
  open-graph:
    site-name: "Proteomics blog"
    description: "A blog for sharing ideas, experiences, and knowledge in proteomics—whatever I’m exploring, working on, or feel like writing about."
    image: "https://lkittinun.github.io/Proteomics/thumbnail_1.png"
  navbar:
    right:
      - text: "Home"
        href: https://lkittinun.github.io
      - about.qmd
      - icon: github
        href: https://github.com/LKittinun/LKittinun.github.io
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

